steps:
# 1. ADIM: Docker Build
# (Değişiklik yok - 'application' klasörünü build et)
- name: 'gcr.io/cloud-builders/docker'
  dir: 'application'
  args:
    - 'build'
    - '-t'
    - '${_ARTIFACT_REGISTRY_PATH}/backend-api:latest'
    - '.'

# 2. ADIM: Docker Push
# (Değişiklik yok - Artifact Registry'ye push'la)
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - '${_ARTIFACT_REGISTRY_PATH}/backend-api:latest'

# 3. ADIM: Cloud Run'a Deploy Et (GÜNCEL / PROXY YÖNTEMİ)
# Bu, 'application/main.go' kodunun 'Proxy Yöntemi' ile
# çalışması için gereken GÜNCEL halidir.
- name: 'gcr.io/google.com/cloudsdktool/google-cloud-cli'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'backend-api' # Terraform'da verdiğimiz Cloud Run servis adı
    - '--image=${_ARTIFACT_REGISTRY_PATH}/backend-api:latest'
    - '--region=${_REGION}'
    - '--platform=managed'
    
    # === MODÜL 5 (PROXY) GÜNCELLEMESİ ===
    # 'main.go' kodumuzun (Proxy yöntemi) ihtiyaç duyduğu YENİ değişkenler:
    # 'DB_HOST' ve 'DB_PORT' eklendi, 'DB_CONN_NAME' env var'dan kalktı.
    # (Değerlerinizi parantezsiz olarak yerleştirdim)
    - '--set-env-vars=DB_USER=app-user,DB_NAME=products-db,DB_HOST=127.0.0.1,DB_PORT=5432,DB_SECRET_ID=projects/634398253577/secrets/db_password/versions/1'
    
    # === PROXY'Yİ EKLEYEN SİHİRLİ SATIR ===
    # Bu komut, Cloud Run'a 'cloud-sql-proxy' sidecar'ını eklemesini söyler
    # ve ona HANGİ veritabanına bağlanacağını söyler:
    - '--add-cloudsql-instances=ozan-gcp-demo:europe-west3:main-db-f0f0b518'

# === DEĞİŞKENLER ===
# (Değişiklik yok)
substitutions:
  _REGION: 'europe-west3'
  _ARTIFACT_REGISTRY_PATH: '${_REGION}-docker.pkg.dev/${PROJECT_ID}/my-backend-repo'

# === GÜVENLİK (MODÜL 2'ye Bağlantı) ===
# (Değişiklik yok)
serviceAccount: 'projects/${PROJECT_ID}/serviceAccounts/cloud-build-sa@${PROJECT_ID}.iam.gserviceaccount.com'

# Yüklenen imajların listesi
# (Değişiklik yok)
images:
  - '${_ARTIFACT_REGISTRY_PATH}/backend-api:latest'

# === GÜVENLİK (MODÜL 4'e Bağlantı) ===
# (Değişiklik yok)
options:
  logging: CLOUD_LOGGING_ONLY